export enum HeroesActionsTypes {
  FETCH_HEROES = 'FETCH_HEROES',
  FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS',
  FETCH_HEROES_ERROR = 'FETCH_HEROES_ERROR'
}

export enum ComicsActionsTypes {
  FETCH_COMICS = 'FETCH_COMICS',
  FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS',
  FETCH_COMICS_ERROR = 'FETCH_COMICS_ERROR'
}
