export const FETCH_HEROES = 'HERO/FETCH_HEROES';
export const FETCH_HEROES_SUCCESS = 'HERO/FETCH_HEROES_SUCCESS';
export const FETCH_HEROES_ERROR = 'HERO/FETCH_HEROES_ERROR';

export const SHOW_LOADER_HEROES = 'HERO/SHOW_LOADER';
export const HIDE_LOADER_HEROES = 'HERO/HIDE_LOADER';

export const FETCH_COMICS = 'COMIC/FETCH_COMICS';
export const FETCH_COMICS_SUCCESS = 'COMIC/FETCH_COMICS_SUCCESS';
export const FETCH_COMICS_ERROR = 'COMIC/FETCH_COMICS_ERROR';

export const SHOW_LOADER_COMICS = 'COMIC/SHOW_LOADER';
export const HIDE_LOADER_COMICS = 'COMIC/HIDE_LOADER';
