export const FETCH_HEROES = 'FETCH_HEROES';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
export const FETCH_HEROES_ERROR = 'FETCH_HEROES_ERROR';

export const HIDE_LOADER_HEROES = 'HIDE_LOADER';

export const FETCH_COMICS = 'FETCH_COMICS';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';
export const FETCH_COMICS_ERROR = 'FETCH_COMICS_ERROR';

export const HIDE_LOADER_COMICS = 'HIDE_LOADER';

